### ISSUE TITLE
no blame reported

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapinho/abapBlame#57]
Just installed, running it against [my own fork of abap2xlsx](https://github.com/AndreaBorgia-Abo/abap2xlsx).

ZBLAME says I'm the only developer and all files appear as 100% mine, for example against zcl_excel_worksheet.clas.abap:
![immagine](https://user-images.githubusercontent.com/25269970/105076534-76803600-5a8b-11eb-9aa9-32fdd272d602.png)

If I clone the repo on my Linux desktop and run "git blame" on the same class I get a reasonable output:
![immagine](https://user-images.githubusercontent.com/25269970/105076660-9f083000-5a8b-11eb-9181-57393a4c0090.png)

Please tell me I am missing some very obvious point! I've tried fiddling with the date / time parameters but no luck.

**Comment by nununo** [comment]
Hello @AndreaBorgia-Abo,

All the versioning this tool does is based on your SAP system versions and not on external git repositories. If you installed abap2xlsx yourself then all the objects are probably owned by you.

Please try again with some Z objects from your system which have been subject of multiple versions and let me know if it makes sense to you.

Cheers!

**Comment by AndreaBorgia-Abo** [comment]
Oh, I completely misunderstood the scope of the project, thanks for the explanation: I came here expecting a "git blame" implementation that leveraged abapGit; it might be a good a idea to point it out in the main page: the abapGit reference really threw me off track.

I am unable to test it: neither in my system because all objects are local (it's the official SAP demo VM), nor in our company server because it is older (complains that... Type "IF_T100_DYN_MSG" is unknown)

**Comment by nununo** [comment]
Oh I see. I'll definitely try to make it more clear in the README.

And yeah, 7.40 is required. It was a hard choice but I figured that every day more and more systems upgrade and 7.40 code is so much cleaner and smaller.

Anyway I hope you get an opportunity to test it in the future.

Cheers!
